### PR TITLE
fix(task-selection): respect archived filter

### LINKED ISSUE #838: Archived projects and tasks show up in selection
Archived tasks and project show up in selection for activities and timesheet.
This shouldn't be the case.
They should only show up in analysis and statistics filter.

image

### PR DESCRIPTION
**Pull request by derrabauke**
Fixes #838 and #839 

The previously refactored task-selection component, did not filter the respective projects and tasks for their current `archived` status. This yielded way more results in the dropdown as expect. Further those results where not ordered and that's why it seemed like it shows some *recent projects / tasks* which in reality, where just the first entries which got previously fetched to the store by other components of the app (e.g. timesheet).

### CODE REVIEW

File: app/components/task-selection/component.js [hunk 1]
```diff
@@ -226,6 +226,22 @@ export default class TaskSelectionComponent extends Component {
...
+  }
+
+  get tasks() {
+    return this.project?.tasks
+      ?.filter((task) => {
+        return this.archived ? true : !task.archived;
+      })
+      .sortBy("name");
+  }
+
```
Comment (StephanH90) [inline app/components/task-selection/component.js:244]:
```suggestion
  get projects() {
    return this.customer?.projects
      ?.filter(filterByArchived)
      .sortBy("name");
  }

  get tasks() {
    return this.project?.tasks
      ?.filter(filterByArchived)
      .sortBy("name");
  }

  filterByArchived(filterable) {
    return this.archived ? true : filterable.archived;
  }
```

if you wanted you could extract the duplicate filter function into a proper function instead.

**Review by StephanH90 — APPROVED** [review]
just 1 np otherwise LGTM

File: app/components/task-selection/component.js (hunk 1 above)
Comment (derrabauke) [reply app/components/task-selection/component.js]: Good points, thanks!
