### PR TITLE
fix: updating the customer, project, task in analysis edit report page

### LINKED ISSUE #1160: changing task/project/customer on a report in analysis broken
When editing a report in the `Analysis` tab, changing the task, project or customer is not possible anymore.

### PR DESCRIPTION
**Pull request by MitanOmar**
fix #1160

### CODE REVIEW

File: app/validators/intersection-task.js [hunk 1]
```diff
@@ -2,11 +2,15 @@ export default function validateIntersectionTask() {
   return (key, newValue, oldValue, changes, content) => {
     const customerChanged =
       Object.keys(changes).includes("customer") &&
-      (changes.customer.id || null) !== (content.customer.id || null);
+      changes.customer &&
+      content.customer &&
+      (changes.customer.id || null) !== (content.customer?.get("id") || null);
```
Comment (derrabauke) [inline app/validators/intersection-task.js:7]:
```suggestion
      (changes.customer?.get("id") || null) !== (content.customer?.get("id") || null);
```

File: app/validators/intersection-task.js [hunk 2]
```diff
@@ -2,11 +2,15 @@ export default function validateIntersectionTask() {
...
 
     const projectChanged =
       Object.keys(changes).includes("project") &&
-      (changes.project.id || null) !== (content.project.id || null);
+      changes.project &&
+      content.project &&
+      (changes.project.id || null) !== (content.project?.get("id") || null);
```
Comment (derrabauke) [inline app/validators/intersection-task.js:13]:
```suggestion
      changes.project?.get("id") !== content.project?.get("id");
```

File: app/validators/intersection-task.js [hunk 3]
```diff
@@ -2,11 +2,15 @@ export default function validateIntersectionTask() {
   return (key, newValue, oldValue, changes, content) => {
     const customerChanged =
       Object.keys(changes).includes("customer") &&
-      (changes.customer.id || null) !== (content.customer.id || null);
+      changes.customer &&
+      content.customer &&
+      (changes.customer.id || null) !== (content.customer?.get("id") || null);
 
     const projectChanged =
       Object.keys(changes).includes("project") &&
```
Comment (derrabauke) [inline app/validators/intersection-task.js:10]: Not need with the following [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator.

File: app/validators/intersection-task.js [hunk 4]
```diff
@@ -2,11 +2,15 @@ export default function validateIntersectionTask() {
   return (key, newValue, oldValue, changes, content) => {
     const customerChanged =
       Object.keys(changes).includes("customer") &&
```
Comment (derrabauke) [inline app/validators/intersection-task.js:4]: Not need with the following [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator.

**Review by derrabauke — COMMENTED** [review]
return (key, newValue, oldValue, changes, content) => {
    const customerChanged =
      Object.keys(changes).includes("customer") &&
      changes.customer &&
      content.customer &&
      (changes.customer.id || null) !== (content.customer?.get("id") || null);

    const projectChanged =
      Object.keys(changes).includes("project") &&
      changes.project &&
      content.project &&
      (changes.project.id || null) !== (content.project?.get("id") || null);

    const hasTask = !!(newValue && newValue.id);

File: app/validators/intersection-task.js (hunk 4 above)
Comment (derrabauke) [reply app/validators/intersection-task.js:4]: I have to correct myself, this line is indeed necessary.

**Review by derrabauke — APPROVED** [review]
