### PR TITLE
fix: bulk report form reset

### LINKED ISSUE #845: bug(bulk-report-edit): edit form doesn't reset properly
# Repro:
Analysis -> filter state: editable --> edit single report -> save --> **Edit all** -> Form has wrong contents.

The contents of the form won't get reset properly when the edit form is entered after previous edits.

Reported by @shurik-io

### PR DESCRIPTION
**Pull request by derrabauke**
Fixes #845 & #844

### CODE REVIEW

File: app/analysis/edit/route.js [hunk 1]
```diff
@@ -1,3 +1,9 @@
 import Route from "@ember/routing/route";
 
-export default class AnalysisEditRoute extends Route {}
+export default class AnalysisEditRoute extends Route {
+  resetController(controller, isExiting, transition) {
+    if (isExiting && transition.targetName !== "error") {
+      controller.send("resetController");
```
Comment (Yelinz) [inline app/analysis/edit/route.js:6]: Isnt it possible to call `controller.resetQueryParams()`

Comment (derrabauke) [reply app/analysis/edit/route.js:6]: :bulb: good one!

Comment (derrabauke) [reply app/analysis/edit/route.js]: `done`
